#!/bin/bash
su - amgdev -c "command -v clangd" &>/dev/null && exit 0

apt-get install -y clang clangd
cat <<EOF > /home/amgdev/.config/nvim-code/lua/custom/cpp.lua
local M = {}

function M.setup_lsp(capabilities)
  vim.lsp.config("clangd", { capabilities = capabilities })
  vim.lsp.enable("clangd")
end

function M.get_formatters_by_ft()
  return {}
end

return M
EOF
