#!/bin/bash
su - amgdev -c "command -v dotnet" &>/dev/null && exit 0

su - amgdev <<'EOF'
    curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
    chmod +x dotnet-install.sh
    ./dotnet-install.sh --version latest
    rm dotnet-install.sh
    echo 'export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools' >> $HOME/.bashrc
    echo 'export DOTNET_ROOT=$HOME/.dotnet' >> $HOME/.bashrc
    echo 'export DOTNET_ROLL_FORWARD=Major' >> $HOME/.bashrc
EOF

