#!/bin/bash
apt-get install -y unzip openjdk-21-jdk
su - amgdev <<'EOF'
    curl -o kotlinlsp.tar.gz https://download-cdn.jetbrains.com/kotlin-lsp/262.4739.0/kotlin-server-262.4739.0.tar.gz
    tar -xzf kotlinlsp.tar.gz -C .kotlin-lsp 
    rm kotlinlsp.tar.gz
    chmod u+x .kotlin-lsp/bin/intellij-server
    mv .kotlin-lsp/bin/intellij-server .kotlin-lsp/bin/kotlin-lsp
    echo 'export PATH=$PATH:$HOME/.kotlin-lsp/bin' >> ~/.bashrc

    curl -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-14742923_latest.zip
    unzip cmdtools.zip 
    rm cmdtools.zip 
    mkdir -p ~/android-sdk/cmdline-tools
    mv cmdline-tools ~/android-sdk/cmdline-tools/latest

    echo "" >> ~/.bashrc
    echo "# Android SDK Configuration" >> ~/.bashrc
    echo 'export ANDROID_HOME=$HOME/android-sdk' >> ~/.bashrc
    echo 'export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin' >> ~/.bashrc
    echo 'export PATH=$PATH:$ANDROID_HOME/platform-tools' >> ~/.bashrc
    
    yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
    ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools"

    curl https://dl.google.com/android/cli/latest/linux_x86_64/android --output android
    chmod u+x android
    mv android ~/android-sdk/cmdline-tools/latest/bin  
EOF
cat <<EOF > /home/amgdev/.config/nvim-code/lua/custom/kotlin.lua
local M = {}

function M.setup_lsp(capabilities)
  vim.lsp.config("kotlin_lsp", { capabilities = capabilities })
  vim.lsp.enable("kotlin_lsp")
end

function M.get_formatters_by_ft()
  return {}
end

return M
EOF
