#!/bin/bash
su - amgdev -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash"
su - amgdev -c "nvm install 25"
su - amgdev -c "npm i -g typescript typescript-language-server"
su - amgdev -c "curl -fsSL https://get.pnpm.io/install.sh | sh -"
cat <<EOF > /home/amgdev/.config/nvim-code/lua/custom/typescript.lua
local M = {}

function M.setup_lsp(capabilities)
  vim.lsp.config("ts_ls", { capabilities = capabilities })
  vim.lsp.enable("ts_ls")
end

function M.get_formatters_by_ft()
  return {}
end

return M
EOF
