#!/bin/bash
cd "$(dirname "$0")"
../setup-python

# TODO Add MCP to opencode config and add symlink to blender
su - amgdev <<'EOF'
    wget -O- https://ftp.nluug.nl/pub/graphics/blender/release/Blender5.2/blender-5.2.0-linux-x64.tar.xz | tar -xJ
    mv blender-5.2.0-linux-x64 /home/amgdev/.bin/blender
    git clone --depth 1 https://projects.blender.org/lab/blender_mcp.git /home/amgdev/.bin/blender-mcp
EOF
