#!/bin/bash
apt-get install -y gpg libicu-dev libcurl4-openssl-dev libedit-dev libsqlite3-dev libncurses-dev libpython3-dev libxml2-dev pkg-config uuid-dev libstdc++-12-dev unzip

su - amgdev <<'EOF'
    curl -O https://download.swift.org/swiftly/linux/swiftly-x86_64.tar.gz
    tar zxf swiftly-$(uname -m).tar.gz
    rm swiftly-$(uname -m).tar.gz
    ./swiftly init --quiet-shell-followup -y --platform debian12
    rm swiftly
    chmod u+x $HOME/.local/share/swiftly/env.sh
    echo ". $HOME/.local/share/swiftly/env.sh" >> $HOME/.bashrc
    mkdir -p $HOME/.config/nvim-code/lua/custom
EOF
cat <<EOF > /home/amgdev/.config/nvim-code/lua/custom/swift.lua
local M = {}

function M.setup_lsp(capabilities)
  vim.lsp.config("sourcekit", { capabilities = capabilities })
  vim.lsp.enable("sourcekit")
end

function M.get_formatters_by_ft()
  return {}
end

return M
EOF
