#!/usr/bin/env python3
import argparse
import sys
import subprocess
import json
import shutil
import os
import glob

parser = argparse.ArgumentParser(description="iOS Development CLI")
subparsers = parser.add_subparsers(dest="command")

config_parser = subparsers.add_parser("config", help="Configure project settings and schemes")
config_parser.add_argument("scheme", nargs='?', default="", help="The scheme to configure")

build_parser = subparsers.add_parser("build", help="Build the app for the iOS simulator")

purge_cache_parser = subparsers.add_parser("purge-cache", help="Delete derived data and clean build artifacts")

a11_parser = subparsers.add_parser("a11", help="Inspector for accessibility labels and traits")

run_parser = subparsers.add_parser("run", help="Install and launch the app on the simulator")

deeplink_parser = subparsers.add_parser("deeplink", help="Open a specific URL scheme or universal link")
deeplink_parser.add_argument("url", help="The URL to open")

logs_parser = subparsers.add_parser("logs", help="Stream live console output from the simulator")

exec_path_parser = subparsers.add_parser("exec-path", help="Get app executable path")
iphone_name_parser = subparsers.add_parser("iphone-name", help="Get the name of the connected iPhone")

args = parser.parse_args()

def get_schemes():
    result = subprocess.run(
        ["xcodebuild", "-list", "-json", "-skipPackageUpdates"],
        capture_output=True,
        text=True,
        check=True
    )
        
    data = json.loads(result.stdout)
        
    project_data = data.get("project") or data.get("workspace")
        
    return project_data.get("schemes", []) if project_data else []

def build():
    with open(".ios/config.json") as f:
        jsonfile = json.load(f)
        scheme = jsonfile["scheme"]
        is_simulator = jsonfile["device"] == "simulator"
    print(f"Building scheme={scheme}...")
    shutil.rmtree(".ios/bundle.xcresult", ignore_errors=True)
    sdk = "iphonesimulator" if is_simulator else "iphoneos"
    options = "-allowProvisioningUpdates" if not is_simulator else ""
    subprocess.run(f"rm -rf .ios/bundle && xcodebuild -scheme {scheme} -sdk {sdk} build {options} -resultBundlePath .ios/bundle | xcbeautify", shell=True, check=True) 

if args.command == "config":
    print("Configuring project...")
    shutil.rmtree(".ios", ignore_errors=True)
    os.makedirs(".ios")
    scheme = args.scheme
    schemes = get_schemes()

    if scheme not in schemes:
        if scheme == "":
            print("No scheme provided")
        else:
            print(f"Scheme {scheme} not found")
        print("Available schemes:")
        for s in schemes:
            print(f"- {s}")
        sys.exit(1)

    with open('.ios/config.json', 'w', encoding='utf-8') as f:
        json.dump({"scheme": scheme, "device": "simulator" }, f, indent=4)

    subprocess.run(["xcode-build-server", "config", "-scheme", scheme], check=True)
    build()
    sys.exit(0)

if args.command == "build":
    build()
    sys.exit(0)

if args.command == "purge-cache":
    paths = [
        "~/Library/Developer/Xcode/DerivedData",
        "~/Library/Caches/CocoaPods",
        "~/Library/Caches/org.swift.swiftpm"
    ]
    
    for path in paths:
        full_path = os.path.expanduser(path)
        if os.path.exists(full_path):
            try:
                shutil.rmtree(full_path)
                print(f"Deleted: {path}")
            except Exception as e:
                print(f"Failed to delete {path}: {e}")
        else:
            print(f"Skipped: {path} (Not found)")

    sys.exit(0)

if args.command == "a11":
    subprocess.run(["open", "-a", "Accessibility Inspector"], check=True)
    sys.exit(0)

if args.command == "run":
    with open(".ios/config.json") as f:
        jsonfile = json.load(f)
        scheme = jsonfile["scheme"]
        is_simulator = jsonfile["device"] == "simulator"
        iphone_name = jsonfile["device"]
    print(f"Running scheme={scheme} on device={jsonfile['device']}...")

    if is_simulator:
        subprocess.run(["open", "-a", "Simulator"], check=True)

    sdk = "iphonesimulator" if is_simulator else "iphoneos"
    xcode_cmd = f"xcodebuild -scheme {scheme} -sdk {sdk} -showBuildSettings"
    result = subprocess.check_output(xcode_cmd, shell=True, text=True)
    
    build_dir = next(
        (line.split("=")[1].strip() for line in result.splitlines() if "TARGET_BUILD_DIR =" in line), 
        None
    )

    bundle_id_cmd = f"xcodebuild -scheme {scheme} -sdk {sdk} -showBuildSettings"
    bundle_id_result = subprocess.check_output(bundle_id_cmd, shell=True, text=True)
    bundle_id = next(
        (line.split("=")[1].strip() for line in bundle_id_result.splitlines() if " PRODUCT_BUNDLE_IDENTIFIER =" in line),
        None
    )

    if build_dir and bundle_id:
        app_paths = glob.glob(os.path.join(build_dir, "*.app"))
        if app_paths[0]:
            if is_simulator:
                subprocess.run(["xcrun", "simctl", "install", "booted", app_paths[0]], check=True)
                subprocess.run(["xcrun", "simctl", "launch", "booted", bundle_id], check=True)
            else:
                subprocess.run(["xcrun", "devicectl", "device", "install", "app", "--device", iphone_name, app_paths[0]], check=True)
                subprocess.run(["xcrun", "devicectl", "device", "process", "launch", "--device", iphone_name, bundle_id], check=True)
    sys.exit(0)

if args.command == "deeplink":
    with open(".ios/config.json") as f:
        jsonfile = json.load(f)
        is_simulator = jsonfile["device"] == "simulator"

    url = args.url
    if is_simulator:
        subprocess.run(["xcrun", "simctl", "openurl", "booted", url], check=True)
    else:
        print("TODO Implement this")
    sys.exit(0)

if args.command == "logs":
    with open(".ios/config.json") as f:
        jsonfile = json.load(f)
        is_simulator = jsonfile["device"] == "simulator"

    try:
        if is_simulator:
            subprocess.run(["xcrun", "simctl", "spawn", "booted", "log", "stream", "--style", "compact"], check=True)
        else:
            print("TODO Implement this")
        sys.exit(0)
    except KeyboardInterrupt:
        pass

if args.command == "exec-path":
    with open(".ios/config.json") as f:
        jsonfile = json.load(f)
        scheme = jsonfile["scheme"]
        is_simulator = jsonfile["device"] == "simulator"
    sdk = "iphonesimulator" if is_simulator else "iphoneos"
    xcode_cmd = f"xcodebuild -scheme {scheme} -sdk {sdk} -showBuildSettings"
    result = subprocess.check_output(xcode_cmd, shell=True, text=True, stderr=subprocess.DEVNULL)
    
    build_dir = next(
        (line.split("=")[1].strip() for line in result.splitlines() if "TARGET_BUILD_DIR =" in line), 
        None
    )
    exec_name = next(
        (line.split("=")[1].strip() for line in result.splitlines() if "TARGET_NAME =" in line), 
        None
    )
    print(f"{build_dir}/{exec_name}.app")
    sys.exit(0)

if args.command == "iphone-name":
    with open(".ios/config.json") as f:
        jsonfile = json.load(f)
        device = jsonfile["device"]
    print(device)
    sys.exit(0)
    
parser.print_help()
