#!/bin/bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew update
brew install xcode-build-server xcodes aria2 xcodegen sweetpad-dev/tap/sweetpad

cd "$(dirname "$0")"
cp lsp.lua $HOME/.config/nvim-code/lua/custom/swift.lua
cp debug.lua $HOME/.config/nvim-debugger/lua/custom/ios.lua
