#!/usr/bin/env python3
import argparse
import sys
import subprocess
import json
import shutil
import os
import glob
from pathlib import Path

parser = argparse.ArgumentParser(description="Android Development CLI")
subparsers = parser.add_subparsers(dest="command")

open_parser = subparsers.add_parser("open", help="Open emulator")

config_parser = subparsers.add_parser("config", help="Configure project settings")
config_parser.add_argument("app_module", nargs='?', default="", help="The app module name")
config_parser.add_argument("flavor", nargs='?', default="", help="The flavor name")
config_parser.add_argument("launch_activity", nargs='?', default="", help="The launch activity package name")

build_parser = subparsers.add_parser("build", help="Build the app")

run_parser = subparsers.add_parser("run", help="Run the app")

deeplink_parser = subparsers.add_parser("deeplink", help="Open a specific URL scheme or app link")
deeplink_parser.add_argument("url", help="The URL to open")

logs_parser = subparsers.add_parser("logs", help="Stream live logcat")
logs_parser.add_argument("-e", action="store_true", help="Show errors only")

metro_parser = subparsers.add_parser("metro", help="Proxy port used for React Native Metro bundler")

talkback_parser = subparsers.add_parser("talkback", help="Manage Talkback")
talkback_parser.add_argument("action", choices=["on", "off"], help="The action to perform")

sms_parser = subparsers.add_parser("sms", help="Send a text message")
sms_parser.add_argument("phone", help="The phone number to send the message to")
sms_parser.add_argument("message", help="The message to send")

pkg_name_parser = subparsers.add_parser("pkg-name", help="Get the package name of the app")

args = parser.parse_args()

def load_config():
    curr = Path.cwd().resolve()
    home = Path.home()
    while True:
        path = curr / ".android/config.json"
        if path.exists():
            return json.loads(path.read_text())
        if curr == home or curr == curr.parent:
            raise FileNotFoundError("Config not found.")
        curr = curr.parent

def find_gradlew():
    curr = Path.cwd().resolve()
    home = Path.home()
    while True:
        path = curr / "gradlew"
        if path.exists():
            return path
        if curr == home or curr == curr.parent:
            raise FileNotFoundError("gradlew not found.")
        curr = curr.parent

def forward_metro():
    subprocess.run(["adb", "reverse", "tcp:8081", "tcp:8081"], check=True)

def launch_emulator():
    output = subprocess.check_output(["emulator", "-list-avds"], text=True)
    avd = output.strip().split('\n')[0]
    print("Using emulator: " + avd)
    subprocess.Popen(["emulator", "-avd", avd, "-accel", "on", "-dns-server", "8.8.8.8,1.1.1.1"], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
    subprocess.run(["adb", "wait-for-device"], check=True)
    forward_metro()

def get_package_name():
    jsonfile = load_config() 
    module = jsonfile["module"]
    flavor = jsonfile["flavor"]
    
    search_path = os.path.join(module, "build", "outputs", "apk", flavor, "debug", "*.apk")
    cmd = ["adb", "shell", "getprop", "ro.product.cpu.abi"]
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    arch = result.stdout.strip()
    apk_paths = glob.glob(search_path)
    apk_path = next((apk for apk in apk_paths if arch in apk), apk_paths[0] if apk_paths else None)
    package_name = subprocess.check_output(["aapt2", "dump", "packagename", apk_path], text=True).strip()
    return package_name

def build():
    jsonfile = load_config()
    gradlew = find_gradlew()
    module = jsonfile["module"]
    flavor = jsonfile["flavor"]
    if flavor == "":
        print(f"Building module={module}...")
        subprocess.run(f"{gradlew} {module}:assembleDebug", shell=True, check=True)
    else:
        print(f"Building module={module}, flavor={flavor}...")
        subprocess.run(f"{gradlew} {module}:assemble{flavor.capitalize()}Debug", shell=True, check=True)

if args.command == "config":
    print("Configuring project...")
    shutil.rmtree(".android", ignore_errors=True)
    os.makedirs(".android")
    app_module = input("App Module (:app): ").strip() or ":app"
    app_module_folder = input("App Module folder (.)").strip() or "." 
    flavor = input("Flavor (optional): ").strip()
    launch_activity = input("Launch Activity: ").strip()
    device = input("Device (emulator/android): ").strip() or "emulator"
    
    with open('.android/config.json', 'w', encoding='utf-8') as f:
        json.dump({
            "module": app_module, 
            "moduleFolder": app_module_folder,
            "flavor": flavor, 
            "launchActivity": launch_activity, 
            "device": device, 
            "launchParams": "" 
        }, f, indent=4)

    build()
    sys.exit(0)

if args.command == "build":
    build()
    sys.exit(0)

if args.command == "run":
    jsonfile = load_config()
    module = jsonfile["module"]
    module_path = jsonfile["moduleFolder"]
    flavor = jsonfile["flavor"]
    launch_activity = jsonfile["launchActivity"]
    is_emulator = jsonfile["device"] == "emulator"
    launch_params = jsonfile["launchParams"]

    print(f"Running module={module}, flavor={flavor}...")

    if is_emulator:
        launch_emulator()
    else:
        forward_metro()
        
    if flavor == "":
        search_path = os.path.join(module_path, "build", "outputs", "apk", "debug", "*.apk")
    else:
        search_path = os.path.join(module_path, "build", "outputs", "apk", flavor, "debug", "*.apk")
    cmd = ["adb", "shell", "getprop", "ro.product.cpu.abi"]
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    arch = result.stdout.strip()
    apk_paths = glob.glob(search_path)
    apk_path = next((apk for apk in apk_paths if arch in apk), apk_paths[0] if apk_paths else None)
    package_name = subprocess.check_output(["aapt2", "dump", "packagename", apk_path], text=True).strip()
    print(f"Installing {apk_path} ({package_name}) on {arch} device...")
    
    subprocess.run(["adb", "install", "--fastdeploy", apk_path], check=True)
    if launch_params != "":
        subprocess.run(f"adb shell am start -n {package_name}/{launch_activity} {launch_params}", shell=True, check=True)
    else:
        subprocess.run(f"adb shell am start -n {package_name}/{launch_activity}", shell=True, check=True)
    
    sys.exit(0)

if args.command == "deeplink":
    url = args.url
    subprocess.run(["adb", "shell", "am", "start", "-a", "android.intent.action.VIEW", "-d", url], check=True)
    sys.exit(0)

if args.command == "logs":
    try:
        subprocess.run(["lazylogcat"], check=True)
        sys.exit(0)
    except KeyboardInterrupt:
        pass

if args.command == "metro":
    forward_metro()
    sys.exit(0)

if args.command == "talkback":
    action = args.action

    if action == "on":
        subprocess.run([
            "adb", "shell", "settings", "put", "secure", 
            "enabled_accessibility_services", 
            "com.google.android.marvin.talkback/com.google.android.marvin.talkback.TalkBackService"
        ], check=True)
    
    elif action == "off":
        subprocess.run([
            "adb", "shell", "settings", "put", "secure", 
            "enabled_accessibility_services", "null"
        ], check=True)
    sys.exit(0)

if args.command == "sms":
    phone = args.phone
    message = args.message
    subprocess.run(["adb", "shell", "cmd", "phone", "sms", "send-sms", phone, f"{message}"], check=True)
    sys.exit(0)

if args.command == "pkg-name":
    print(get_package_name())

    sys.exit(0)

if args.command == "open":
    launch_emulator()
    sys.exit(0)

parser.print_help()
