#!/bin/bash
su - amgdev -c "command -v adb" &>/dev/null && exit 0

cd "$(dirname "$0")"
apt-get install -y unzip openjdk-21-jdk-headless
su - amgdev <<'EOF'
    KOTLIN_LSP_VERSION=$(curl -s https://api.github.com/repos/Kotlin/kotlin-lsp/releases/latest | grep -Po '"name"\s*:\s*"v\K[^"]*')
    curl -L -o kotlinlsp.tar.gz https://download-cdn.jetbrains.com/language-server/kotlin-server/$KOTLIN_LSP_VERSION/kotlin-server-$KOTLIN_LSP_VERSION.tar.gz
    tar -xzf kotlinlsp.tar.gz
    rm kotlinlsp.tar.gz
    mv kotlin-server-$KOTLIN_LSP_VERSION ~/.bin/kotlin-server
    echo "$HOME/.bin/kotlin-server/bin/intellij-server" > ~/.bin/kotlin-lsp
    chmod u+x ~/.bin/kotlin-lsp

    curl -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-15859902_latest.zip
    unzip cmdtools.zip 
    rm cmdtools.zip
    mkdir -p ~/android-sdk/cmdline-tools
    mv cmdline-tools ~/android-sdk/cmdline-tools/latest

    echo "" >> ~/.bashrc
    echo "# Android SDK Configuration" >> ~/.bashrc
    echo 'export ANDROID_HOME=$HOME/android-sdk' >> ~/.bashrc
    echo 'export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin' >> ~/.bashrc
    echo 'export PATH=$PATH:$ANDROID_HOME/platform-tools' >> ~/.bashrc
    
    ~/android-sdk/cmdline-tools/latest/bin/android sdk install platform-tools

    curl https://github.com/parfenovvs/lazylogcat/releases/download/v0.14.0/lazylogcat_0.14.0_linux_amd64.tar.gz -L -o lazylogcat.tar.gz
    tar -xzf lazylogcat.tar.gz
    rm lazylogcat.tar.gz
    mv lazylogcat ~/.bin
EOF
cp lsp.lua /home/amgdev/.config/nvim-code/lua/custom/kotlin.lua 
chown amgdev:amgdev /home/amgdev/.config/nvim-code/lua/custom/kotlin.lua 
cp debug.lua /home/amgdev/.config/nvim-debugger/lua/custom/android.lua
chown amgdev:amgdev /home/amgdev/.config/nvim-debugger/lua/custom/android.lua

